/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html'),
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  }),
);

// Runtime caching for common map tile providers (cross-origin)
// This improves repeat navigation performance and resilience when the network is flaky.
registerRoute(
  ({ url }) =>
    (/(?:^|\.)tile\.openstreetmap\.org$/i.test(url.hostname) ||
      /(?:^|\.)basemaps\.cartocdn\.com$/i.test(url.hostname) ||
      /(?:^|\.)arcgisonline\.com$/i.test(url.hostname)) &&
    /\.(?:png|jpg|jpeg|webp)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: 'map-tiles',
    plugins: [
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 7 * 24 * 3600 }), // keep up to 7 days
    ],
  }),
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

const parsePushPayload = (event) => {
  if (!event || !event.data) return {};
  try {
    return event.data.json();
  } catch (_) {
    try {
      const text = event.data.text();
      return text ? JSON.parse(text) : {};
    } catch (err) {
      return {};
    }
  }
};

const formatEqNotification = async (payload) => {
  const data = (payload && payload.data) || payload || {};
  const eventType = String(data.eventType || data.type || '').toUpperCase();
  const isUpdate = eventType === 'UPDATE';
  const publicID = data.publicID || data.publicId || data.id;
  const tag = publicID ? `eq:${publicID}` : undefined;
  let updateCount = 0;
  if (isUpdate && tag) {
    try {
      const existing = await self.registration.getNotifications({ tag });
      if (existing && existing.length) {
        const prev = existing[0]?.data?.updateCount;
        updateCount = Number.isFinite(prev) ? prev + 1 : 2;
      } else {
        updateCount = 1;
      }
    } catch (_) {
      updateCount = 1;
    }
  }
  const magnitudeRaw = data.magnitude_value ?? data.magnitude ?? data.mag;
  const magnitudeValue = Number(magnitudeRaw);
  const magText = Number.isFinite(magnitudeValue) ? `M${magnitudeValue.toFixed(1)}` : 'Magnitude unknown';
  const placeRaw = data.place || data.text || data.location || '';
  const place = String(placeRaw || '').trim();
  const locationText = place || 'Unknown location';
  const updateLabel = isUpdate && updateCount ? `Update #${updateCount}` : '';
  const baseTitle = payload && payload.title ? String(payload.title) : 'Earthquake Alert';
  const title = isUpdate && updateCount ? `${baseTitle} #${updateCount}` : baseTitle;
  const baseBody = payload && payload.body ? String(payload.body) : `${magText} in ${locationText}`;
  const body = isUpdate && updateLabel ? `${updateLabel} • ${baseBody}` : baseBody;
  const url = data.url || (publicID ? `/?event=${encodeURIComponent(publicID)}` : '/');
  return {
    title,
    options: {
      body,
      tag,
      renotify: isUpdate,
      data: {
        url,
        publicID,
        eventType,
        updateCount,
      },
    },
  };
};

self.addEventListener('push', (event) => {
  event.waitUntil((async () => {
    const payload = parsePushPayload(event);
    const { title, options } = await formatEqNotification(payload);
    await self.registration.showNotification(title, options);
  })());
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = event.notification?.data?.url || '/';
  const absoluteUrl = new URL(targetUrl, self.location.origin).href;
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url && client.url.startsWith(self.location.origin) && 'focus' in client) {
          return client.focus().then(() => {
            if (client.url !== absoluteUrl && 'navigate' in client) {
              return client.navigate(absoluteUrl);
            }
            return client;
          });
        }
      }
      if (clients.openWindow) return clients.openWindow(absoluteUrl);
      return undefined;
    }),
  );
});

// Any other custom service worker logic can go here.
